Global $STRINGS_Title = "File Merger"
Global $STRINGS_Browse = "Browse..."
Global $STRINGS_SelectSource = "Select Source Folder"
Global $STRINGS_SelectDestination = "Select Destination Folder"
Global $STRINGS_Merge = "Merge Files"
Global $STRINGS_MergeCompleteTitle = "Merge Complete"
Global $STRINGS_MergeCompleteMsg = "Files merged successfully for type: "
